### ISSUE TITLE
pTeX のドキュメント化

### ISSUE THREAD

**Issue by aminophen** [texjporg/ptex-base#2]
あべのりさんが発見されたようですが，アスキー pTeX のサイト http://ascii.asciimw.jp/pb/ptex/index.html が閉鎖？されているようです。また，韓国 KTUG のサイトも閉鎖？され，DVIPDFMx の cvs 版の頃のリポジトリや The Asian Journal of TeX http://ajt.ktug.kr/ のアーカイブもアクセス不能になっています。pTeX のプリミティブなどのドキュメントはもともと不足しているので，何か TeX Live からアクセス可能なドキュメントを追加できればよいのですが，texjporg で pTeX のドキュメント化を進めることができないでしょうか？

**Comment by kmaed** [comment]
> アスキー pTeX のサイト http://ascii.asciimw.jp/pb/ptex/index.html が閉鎖？

[Internet Archive](http://web.archive.org/web/20160508004851/http://ascii.asciimw.jp/pb/ptex/index.html) から拾えますね．プリミティブは [zz.html](http://web.archive.org/web/20151128183448/http://ascii.asciimw.jp:80/pb/ptex/help/zz.html) に．

ptex-base でまとめるのはよいと思いますが，元の資料のライセンスがよくわからないのがちょっと難点かも．

**Comment by aminophen** [comment]
> 元の資料のライセンスがよくわからない

一部引用に留めつつ書き起こすのが無難でしょうね。ptex-manual.{tex,pdf} のような名称がよいと思いますが，手始めにプリミティブの一覧を作るところから始めてはどうか，と思っています。（プリミティブについてはアスキーのサイトに載っていなかったものも多々あり，texconf16 で初めて北川さんがまとめてくださったので，参考にさせていただきたいと思います）

**Comment by munepi** [comment]
2015年6月27日の時点で、アスキーpTeXのサイト丸ごと `wget -np -m` したデータは取ってあります。

The Asian Journal of TeXのサイト閉鎖の件は、ChoFさんに聞いてみたほうがよさそうです。

> 手始めにプリミティブの一覧を作るところから始めてはどうか，
+1します！

**Comment by h-kitagawa** [comment]
> 手始めにプリミティブの一覧を作るところから始めてはどうか，
> +1します！

私も +1．

せっかく新しく書き起こすのであれば，今問題になっている texjporg/tex-jp-build#11 で述べているような，細かい仕様までまとめられたらいいですね！

**Comment by aminophen** [comment]
みなさま，コメントありがとうございます。

種類別に分類して章立てを作った方がよいかと思って

- 文字間のスペース
    - \kanjiskip \xkanjiskip
    - \xspcode \inhibitxspcode
    - \autospacing \noautospacing \autoxspacing \noautoxspacing \showmode
    - \inhibitglue
- 禁則
    - \prebreakpenalty \postbreakpenalty
    - \jcharwidowpenalty
- 組方向
    - \tate \yoko \dtou
    - \iftdir \ifydir \ifddir \ifmdir
    - \iftbox \ifybox \ifdbox \ifmbox
- ベースライン補正
    - \tbaselineshift \ybaselineshift
    - \textbaselineshiftfactor \scriptbaselineshiftfactor \scriptscriptbaselineshiftfactor
- 和文ファミリ
    - \jfam \jfont \tfont
    - \kcatcode
- 文字コード変換
    - \kuten \jis \euc \sjis
    - \kansuji \kansujichar
- 長さ単位
    - zw zh

という感じでしょうか？

**Comment by aminophen** [comment]
> pTeX のプリミティブ一覧

ほぼ目次だけ，の ptex-manual.tex を https://github.com/texjporg/ptex-manual に置きました。（UTF-8 encoding にして置いたほうが GitHub から見やすいと思ったので別リポジトリを立てましたが，最終的には ptex-base に含めてしまえばよいと思っています。）

**Comment by kmaed** [comment]
ありがとうございます．

すぐ気付いたこととして，最後の参考文献の URL  が 
```http://tug.org/pipermail/xetex/2015-July/026044.html```
となっているのですが，
```https://github.com/texjporg/platex/issues/22```
の間違いではないかと思います．

**Comment by aminophen** [comment]
横着して eptexdoc.tex から貼り付けたのがバレてしまうマチガイですね… ありがとうございます。

**Comment by aminophen** [comment]
> ptex-manual.tex を https://github.com/texjporg/ptex-manual に置きました。（UTF-8 encoding にして置いたほうが GitHub から見やすいと思ったので別リポジトリを立てましたが，最終的には ptex-base に含めてしまえばよいと思っています。）

と書いたのですが，今ごろになって「別に ptex-base に含めなくても，ptex-manual のままリリースしてもいいのではないか？」と思いつきました。むしろ，いま ptex-base にある（もともとアスキーが書いた）ドキュメントを全部 ptex-manual に移し，UTF-8 に変更するのもアリではないかと思っています。

- ptex-base: フォーマット作成用ファイルと README だけ
    - ドキュメントは ptex-manual にある，と導線を張る。
- ptex-manual: ドキュメント類 (.tex, .pdf)

その方が何かと便利そうですが，いかがでしょう？

**Comment by aminophen** [comment]
とりあえず ptex-manual を単独で CTAN に登録申請しました。次に ptex-base を出すときには，ドキュメントは全部 ptex-base に移動させることも視野に考えます。

**Comment by aminophen** [comment]
ptex-base にあったドキュメント類は全部 ptex-manual へ移動しました。そのほうが UTF-8 に統一できてブラウザ上で読めるので。こちらの issue は閉じます。
