### ISSUE TITLE
A typo in *pTeX's error message

### ISSUE THREAD

**Issue by Man-Ting-Fang** [texjporg/ptex-base#6]
`I refuse to unbox a box in differrent direction.`: differrent -> different

(Spelling in Knuth's `tex.web` is correct. However, the expression is different:
```
I refuse to unbox an \hbox in vertical mode or vice versa.
And I can't open any boxes in math mode.
```
)

**Comment by aminophen** [comment]
Thanks for reporting, I'll fix

> Spelling in Knuth's tex.web is correct. However, the expression is different:

That is an error message in the different case, which is still available from pTeX. The error message with typo is an addition (not a replacement) by pTeX.

**Comment by Man-Ting-Fang** [comment]
> That is an error message in the different case, which is still available from pTeX. The error message with typo is an addition (not a replacement) by pTeX.

Thank you! I know little about that...

**Comment by aminophen** [comment]
Opened pull request texjporg/tex-jp-build#20; if agreed, the owner (or I) will commit to TeX Live svn when time comes...

**Comment by aminophen** [comment]
Done, [TeX Live r45237](https://www.tug.org/svn/texlive?view=revision&revision=45237), along with other improvements in pTeX direction change commands discussed at texjporg/tex-jp-build#21.
