### ISSUE TITLE
デフォルトで縦組用和文フォントが設定されていない

### ISSUE THREAD

**Issue by h-kitagawa** [texjporg/ptex-base#7]
`ptex.tex` を見ると，

 * デフォルトの和文フォントは `\mc`
 * `\mc`, `\gt` は，現在の組方向に応じて縦組用和文フォントか横組用和文フォントか片方しか変えない

という仕様になっています．そのため，
```
あいうえお\hbox{\tate かきくけこ}
```
とだけ書いても，縦組用和文フォントが設定されていないために，後半の縦組ボックス中の和文文字が何一つ出力されない状況となっています．

数式フォントをどうするかは悩むところですが，次のように `\mc`, `\gt` で両方の組方向の和文フォントを設定することには何か不都合があるのでしょうか？
```
\def\mc{%
  \iftdir\fam\tminfam\else\fam\minfam\fi% 数式フォント
  \tentmin\tenmin}%
```

**Comment by aminophen** [comment]
両方設定しても不都合はないでしょうし、その方が使いやすくていいと思います。
