### ISSUE TITLE
\inhibitxspcode`！ の設定がない

### ISSUE THREAD

**Issue by h-kitagawa** [texjporg/ptex-base#8]
疑問符については kinsoku.tex に
```
\prebreakpenalty`?=10000
\prebreakpenalty`？=10000
\inhibitxspcode`？=1
```
という設定があるのに，感嘆符については
```
\prebreakpenalty`!=10000
\prebreakpenalty`！=10000
``` 
しかなく，```\inhibitxspcode`！=1``` が抜けています．これは意図的でしょうか？

もともとは LuaTeX-ja のチケット「[「！」の前の xkanjiskip](https://osdn.net/projects/luatex-ja/ticket/40661)」ですが，pTeX 系列の kinsoku.tex でも同様の症状があるので，ここで述べておきます．

**Comment by aminophen** [comment]
意図的かどうかはよくわかりません。jsclasses では

``` tex
% 「\TeX！」「〒515」の記号と数字の間に四分アキが入らないようにします。
%
%    \begin{macrocode}
\inhibitxspcode`！=1
\inhibitxspcode`〒=2
%    \end{macrocode}
%
```

としてありますね。

**Comment by aminophen** [comment]
JFM と考え合わせると，min10 だと "！" が前後に JFM グルー挿入を行うため「実質的に \inhibitxspcode`！ を忘れていても露呈するケースは少ない」と言えそうです。（ただし，min10 では "？" も同様に前後に JFM グルー挿入を行うため，これが「意図的に "！" を外した理由」と推測するのは無理がある）

一方 jis だと JFM グルーが挿入されないので，設定忘れが露呈します。jsclasses で設定追加されているのも納得。

**Comment by aminophen** [comment]
このような状況ですので，(u)kinsoku.tex に

``` tex
\inhibitxspcode`！=1
```

を追加しても，既存文書への影響は限定的であり，むしろ追加するのが好ましいと考えます。

**Comment by aminophen** [comment]
ptex-base, platex, uptex-base, uplatex すべて "！" の \inhibitxspcode を 1 に設定しました。

**Comment by aminophen** [comment]
修正した ptex-base / uptex-base 2020-09-30 を出しました。

platex / uplatex も本日リリース予定です。
