### ISSUE TITLE
\inhibitxspcode`： の設定がない 

### ISSUE THREAD

**Issue by h-kitagawa** [texjporg/ptex-base#9]
全角セミコロンについては kinsoku.tex に
```
\prebreakpenalty`；=10000
\inhibitxspcode`；=1
```
という設定があるのに，全角コロンについては
```
\prebreakpenalty`：=10000
```
しかありませんが，これは意図的なものでしょうか？

#8 と同様に，もとは LuaTeX-ja のチケット 「[「：」の前の xkanjiskip](https://osdn.net/projects/luatex-ja/ticket/41670)」ですが，pTeX 系列の kinsoku.tex でも同様の症状があるので．

**Comment by aminophen** [comment]
確かに，抜けていますね。意図的だとは思わないので，追加して良いのではないでしょうか。（前回の #8 と同様にやはり JFM グルー挿入時には \inhibitxspcode がなくても露呈しなかったと思われます。）

**Comment by h-kitagawa** [comment]
というわけで efa267d152f0b8ce7e554a54380e5bf886b05eda で追加しました．
欧文文字に対する `\xspcode` も，「;」はあるのに「:」はなかったので，こちらも加えています．

**Comment by h-kitagawa** [comment]
pLaTeX 側にも反映 (https://github.com/texjporg/platex/commit/5db1ffddf3512f57d1b100f66bb1a3b5a9885141 )．LuaTeX-ja にも同様の変更を後で加えます．

**Comment by aminophen** [comment]
ありがとうございます。uptex-base, uplatex にも追加しました。

**Comment by aminophen** [comment]
本日，この issue に絡むものは全部リリースします。
